name: crpt_app_0
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.3
  dio: ^5.9.1
  get_it: ^9.2.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  talker_flutter: ^5.1.13
  talker_dio_logger: ^5.1.13
  talker_bloc_logger: ^5.1.13
  firebase_core: ^4.4.0
  json_annotation: ^4.8.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  auto_route: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.6.1
  build_runner:
  hive_generator: ^2.0.0
  auto_route_generator: ^6.1.0


flutter:
  uses-material-design: true
  assets:
    - assets/svg/